name: Create PDF.

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make PDF
      run: |
        # Install dependencies
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq \
        xfonts-base \
        xfonts-75dpi \
        < /dev/null > /dev/null
        # Download
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb
        # Run
        wkhtmltopdf https://joaorodrigues.github.io/git-cheat-sheet/ git-cheat-sheet.pdf
        # Push PDF
        git config --global user.name 'Autobot'
        git config --global user.email 'joaorodrigues@users.noreply.github.com'
        git add git-cheat-sheet.pdf
        git commit -m "Automated PDF"
        git push
